apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentforge-gov
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - nats.yaml
  - nats-worker-deploy.yaml
  - tool-executor-deploy.yaml
  - orchestrator-deploy.yaml
  - results-sink-deploy.yaml
  - pgvector.yaml
  - network-policies.yaml
  - rbac.yaml
  - servicemonitors.yaml
patches:
  - path: patches/fips-annotations.yaml
