apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: agentforge-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: agentforge-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: agentforge-staging
---
