apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
  - name: cuda-vector-add
    image: nvidia/samples:vectoradd-cuda11.6.1
    resources:
      limits:
        nvidia.com/gpu: 1 # request 1 GPU
  restartPolicy: OnFailure
